version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.1
    container_name: logstash
    # environment:
      # - setup.kibana.host=kibana:5601
    volumes:
      - ${PWD}/config/logstash/pipeline:/usr/share/logstash/pipeline:ro
      # - ${PWD}/config/mapping/index_mapping.json:/usr/share/elasticsearch/mappings/index_mapping.json:ro       
    networks:
      - esnet      
networks:
  esnet: